#
# Makefile Huawei Honor Drivers
#

# Each configuration option enables a list of files.

obj-$(CONFIG_HUAWEI_KERNEL)	+= compass/
obj-$(CONFIG_HUAWEI_KERNEL)	+= gyroscope/
obj-$(CONFIG_HUAWEI_KERNEL)	+= proximity/
obj-$(CONFIG_HUAWEI_FEATURE_INPUT_ACCELEROMETER)	+= accelerometer/


